<div class="">
<div class="navbar navbar-dark bg-dark">
<div class="col-sm-8 text-light"><h2>Editar categorias</h2></div>
<div class="col-sm-4">
	<a href="<?php echo APP_URL.'tareas'; ?>">
		<button class="btn btn-sm btn-primary">
			<span class="fa fa-plus"></span> Lista de tareas
		</button>
	</a>
	<a href="<?php echo APP_URL.'tareas/agregar'; ?>">
		<button class="btn btn-sm btn-primary">
			<span class="fa fa-plus"></span> Tarea
		</button>
	</a>
	<a href="<?php echo APP_URL.'categorias/agregar'; ?>">
		<button class="btn btn-sm btn-primary">
			<span class="fa fa-plus"></span> Categoria
		</button>
	</a>
</div>				
</div>
</div>
<div class="container">
	<div class="col-md-6 mx-auto">		
		<form action="<?php echo APP_URL."categorias/editar"; ?>" method="POST">
			<input type="hidden" name="id" value="<?php echo $this->categoria["id"]; ?>">
			<div class="form-group">
				<label for="nombre">Nombre</label>
				<input type="text" name="nombre" class="form-control" value="<?php echo $this->categoria["nombre"]; ?>">
			</div>
			<div class="form-group">
				
			</div>
			<button type="submit" class="btn btn-primary"><span class="fa fa-check"></span> Guardar</button>
		</form>
	</div>
</div>
